name: py311-tftxtrans
channels:
  - conda-forge
dependencies:
  - python=3.11.3
  - pip
  - pip:
    - click>=8.1.3
    - tensorflow>=2.12.0
    - tensorflow-datasets>=4.9.2
    - transformers>=4.31.0
    - ruff>=0.0.271
    - yapf>=0.33.0
    - isort>=5.12.0
    - pytest>=7.3.1
    - pytest-cov>=4.1.0
    - ipython
    - jedi-language-server
